spring:
  profiles:
    active: dev
server:
  port: 8081
  servlet:
    context-path: /weixinxcx
mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.springboot.weixinxcx.entity
  config-location: mybatis-config.xml